### 
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "waka@drwaka.com",
    "password": "outra-senha"
}

### 
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "erro@senha-invalida.com",
    "password": "1234"
}

### 
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "email-invalido",
    "password": "123456789123"
}