@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzYmRiMTg1MC1hYmEyLTQwZGMtYWE0Ni04MzBmOTlhZjc5NjQiLCJpYXQiOjE3NTQ3NTE0OTgsImV4cCI6MTc1NDc1NTA5OH0.1Wjjta9drmXmdHN3O9hj3OWVAKypZKp2uN45jE2GUho

###
GET http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

### user unauthorized
GET http://localhost:3000/users/me
Content-Type: application/json